# Generated by Django 5.0.6 on 2024-06-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='availabilityStatus',
            field=models.CharField(default='In progress', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='To be determined', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='To be determined'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(default='no'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_information',
            field=models.TextField(default='To be determined'),
        ),
    ]
