# Generated by Django 5.0.6 on 2024-06-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_thumbnail_product_availabilitystatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(default='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'),
        ),
    ]
