# Generated by Django 5.0.6 on 2024-06-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(default=dict),
        ),
    ]
