# Generated by Django 5.0.6 on 2024-07-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_stock_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availabilityStatus',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(default='In progress', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(default='To be determined', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_information',
            field=models.CharField(default='To be determined', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_information',
            field=models.CharField(default='To be determined', max_length=255),
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField()),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
        ),
    ]
