# Generated by Django 5.2.3 on 2025-09-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_source', models.CharField(default='footer', max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('preferences', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='products_ne_email_ef14a8_idx'), models.Index(fields=['is_active'], name='products_ne_is_acti_8cfd57_idx'), models.Index(fields=['subscribed_at'], name='products_ne_subscri_ecc807_idx')],
            },
        ),
    ]
