# Generated by Django 5.2.3 on 2025-09-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('promotional', 'Promotional'), ('newsletter', 'Newsletter'), ('announcement', 'Announcement'), ('custom', 'Custom')], default='newsletter', max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('html_content', models.TextField()),
                ('plain_text_content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template_type', 'is_active'], name='products_ne_templat_0d2abb_idx'), models.Index(fields=['is_active'], name='products_ne_is_acti_355770_idx'), models.Index(fields=['created_at'], name='products_ne_created_e64dcb_idx')],
            },
        ),
    ]
