# Generated by Django 5.2.3 on 2025-09-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_newslettertemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterTemplate',
            new_name='EmailTemplate',
        ),
        migrations.RenameIndex(
            model_name='emailtemplate',
            new_name='products_em_templat_7a0516_idx',
            old_name='products_ne_templat_0d2abb_idx',
        ),
        migrations.RenameIndex(
            model_name='emailtemplate',
            new_name='products_em_is_acti_ef7e2d_idx',
            old_name='products_ne_is_acti_355770_idx',
        ),
        migrations.RenameIndex(
            model_name='emailtemplate',
            new_name='products_em_created_e92086_idx',
            old_name='products_ne_created_e64dcb_idx',
        ),
    ]
