# Generated by Django 5.2.3 on 2025-09-23 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_newsletter_template_to_email_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('new_user_welcome', 'New User Welcome'), ('newsletter_send', 'Newsletter Sending'), ('promotional_campaign', 'Promotional Campaign'), ('product_announcement', 'Product Announcement'), ('system_notification', 'System Notification'), ('custom_use', 'Custom Use')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='products.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Template Assignment',
                'verbose_name_plural': 'Email Template Assignments',
                'ordering': ['purpose'],
            },
        ),
    ]
